site_name: EVKafka

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    - scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Overview: 'index.md'
  - Endpoints: 'endpoint.md'
  - Handlers: 'handlers.md'
  - Consumers: 'consumers.md'
  - Producers: 'producers.md'
  - Lifespan: 'lifespan.md'
  - Middleware: 'middleware.md'
  - Testing: 'testing.md'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

repo_url: https://github.com/theleharo/evkafka
repo_name: theleharo/evkafka
site_url: https://evkafka.readthedocs.io/en/stable/
